version: "3.5"

services:
  message-service:
    container_name: message-service
    build:
      context: ./
      dockerfile: Dockerfile
    image: message-service
    ports:
      - "8084:8080"
    depends_on:
      - message-service_database
    networks:
      - noodlee-system-network

  message-service_database:
    container_name: message-service_database
    image: postgres:9.6
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PFmte}vA*88`&"26
      POSTGRES_DB: messages
    volumes:
      - message-service_database-volume:/var/lib/postgresql/message
    networks:
      - noodlee-system-network

networks:
  noodlee-system-network:
    name: noodlee-system-network
    driver: bridge
    
volumes:
  message-service_database-volume:
